### ISSUE TITLE
Seek API changing in next server reboot to support time increment 

### ISSUE THREAD

**Issue by chaitu236** [scottven/TakBot#2]
Please check https://github.com/chaitu236/TakServer for API

**Comment by scottven** [comment]
Is the change just that users can now request black or white?  I don't think that impacts TakBot since it never makes seeks, just accepts them.  I see the "seek new" also includes the color request, but TakBot already ignores anything past the username.

**Comment by chaitu236** [comment]
No this change is to specify the amount of time increment after every move. The seek list and seek remove commands will change so it might affect TakBot depending on how your code is.

**Comment by chaitu236** [comment]
I just tested it and it works fine with new API
